JFBlog/urls.py
from django.contrib import admin
from django.urls import path, include
from article import views
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from django.contrib.sitemaps.views import sitemap
from django.contrib.sitemaps import GenericSitemap
from article.models import Article, Category
from django.views.generic import TemplateView

info_dict = {
    'queryset': Article.objects.all(),
    'data_field': 'pub_date',
}

info2_dict = {
    'queryset': Category.objects.all(),
    'data_field': 'pub_date',
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name = "index"),
    path('about/', views.about, name = "about"),
    path('categories/', views.categories, name = "cats"),
    path('articles/', include("article.urls")),
    path('user/', include("user.urls")),
    path('<slug:slug>/', views.show_category, name='category'),
    path('<slug:slug>/<slug:title>/', views.details, name = "details"),
    path('sitemap.xml/', sitemap, {'sitemaps': {'article': GenericSitemap(info_dict, priority=0.8), 'cat': GenericSitemap(info2_dict, priority=0.8)}}, name='django.contrib.sitemaps.views.sitemap'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += [
    url(r'^robots\.txt$', TemplateView.as_view(template_name="robots.txt", content_type='text/plain')),
]

article/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "article"

urlpatterns = [
    path('dashboard/', views.dashboard, name = "dashboard"),
    path('addarticle/', views.addarticle, name = "addarticle"),
    path('update/<int:id>', views.updateArticle, name = "update"),
    path('delete/<int:id>', views.deleteArticle, name = "delete"),
    path('comment/<int:id>', views.addComment, name = "comment"),
    path('', views.articles, name = "articles"),
]

user/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "user"

urlpatterns = [
    path('register/', views.register, name = "register"),
    path('login/', views.loginUser, name = "login"),
    path('logout/', views.logoutUser, name = "logout"),
]

templates/includes/navbar.html
<nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse">
    <div class="container" style="width: 2000px;">
        <ul class="navbar-nav mr-auto" style = "padding-left: 55px;">
          <a class="navbar-brand" href="{% url 'index' %}">JFBlog</a>
        </ul>
        <ul class="navbar-nav ml-auto" style = "padding-right: 55px;">
	<li class="nav-item dropdown">
        	<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          		Son
        	</a>
        	<div class="dropdown-menu" aria-labelledby="navbarDropdown">
			<a class="dropdown-item" href="{% url 'article:articles' %}"><i class="fas fa-laptop-code"></i> Yazılarım</a>
			<a class="dropdown-item" href="/travels"><i class="fas fa-globe-europe"></i> Gezilerim</a>
          		<a class="dropdown-item" href="/mixes"><i class="fas fa-headphones"></i> Mixlerim</a>
          		<div class="dropdown-divider"></div>
          		<a class="dropdown-item" href="{% url 'about' %}"><i class="fas fa-info-circle"></i> Hakkımda</a>
        	</div>
     	  </li>
	  <li class="nav-item active">
            <a class="nav-link" href="/categories">Kategoriler </a>
          </li>
          <li class="nav-item active">
            <form class="form-inline" style="float: right;">
              {% csrf_token %}
              <input class="form-control mr-sm-2" type="text" name="keyword" placeholder="Ara" aria-label="Search">
            </form>
          </li>
        </ul>
    </div>
</nav>