JFBlog/urls.py
from django.contrib import admin
from django.urls import path, include
from article import views
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from django.contrib.sitemaps.views import sitemap
from django.contrib.sitemaps import GenericSitemap
from article.models import Article, Category
from django.views.generic import TemplateView

info_dict = {
    'queryset': Article.objects.all(),
    'data_field': 'pub_date',
}

info2_dict = {
    'queryset': Category.objects.all(),
    'data_field': 'pub_date',
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name = "index"),
    path('about/', views.about, name = "about"),
    path('categories/', views.categories, name = "cats"),
    path('articles/', include("article.urls")),
    path('user/', include("user.urls")),
    path('<slug:slug>/', views.show_category, name='category'),
    path('<slug:slug>/<slug:title>/', views.details, name = "details"),
    path('sitemap.xml/', sitemap, {'sitemaps': {'article': GenericSitemap(info_dict, priority=0.8), 'cat': GenericSitemap(info2_dict, priority=0.8)}}, name='django.contrib.sitemaps.views.sitemap'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += [
    url(r'^robots\.txt$', TemplateView.as_view(template_name="robots.txt", content_type='text/plain')),
]

article/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "article"

urlpatterns = [
    path('dashboard/', views.dashboard, name = "dashboard"),
    path('addarticle/', views.addarticle, name = "addarticle"),
    path('update/<int:id>', views.updateArticle, name = "update"),
    path('delete/<int:id>', views.deleteArticle, name = "delete"),
    path('comment/<int:id>', views.addComment, name = "comment"),
    path('', views.articles, name = "articles"),
]

user/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "user"

urlpatterns = [
    path('register/', views.register, name = "register"),
    path('login/', views.loginUser, name = "login"),
    path('logout/', views.logoutUser, name = "logout"),
]

article/models.py
from django.db import models
from ckeditor.fields import RichTextField

class Category(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField()
    slug2 = models.CharField(max_length = 200, null = True)
    parent = models.ForeignKey('self',blank=True, null=True, on_delete = models.CASCADE, related_name='children')

    class Meta:
        unique_together = ('slug', 'parent',)    #enforcing that there can not be two
        verbose_name_plural = "categories"       #categories under a parent with same 
                                                 #slug 

    def __str__(self):                           # __str__ method elaborated later in
        full_path = [self.name]                  # post.  use __unicode__ in place of
                                                 # __str__ if you are using python 2
        k = self.parent                          

        while k is not None:
            full_path.append(k.name)
            k = k.parent

        return '/'.join(full_path[::-1])

    def get_absolute_url(self):
        url = "/" + self.slug
        return url


class Article(models.Model):
    author = models.ForeignKey("auth.User", on_delete = models.CASCADE, verbose_name = "Yazar")
    category = models.ForeignKey('Category', on_delete = models.CASCADE, null=True, blank=True)
    title = models.CharField(max_length = 50, verbose_name = "Başlık")
    content = RichTextField(verbose_name = "İçerik")
    created_date = models.DateField(auto_now_add= True, verbose_name = "Tarih")
    article_image = models.FileField(blank = True, null = True, verbose_name = "Resim Ekle")
    seo = models.CharField(max_length = 100, verbose_name = "Seo", null = True)
    read = models.CharField(max_length = 50, verbose_name = "Read", null = True)
    views = models.IntegerField(verbose_name = "View", null = True)

    def __str__(self):
        return self.title

    class Meta():
        ordering = ['-id']

    def get_absolute_url(self):
        url = "/" + self.category.slug + "/" + self.seo
        return url

class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete = models.CASCADE, verbose_name = "Yazı", related_name= "comments")
    comment_author = models.CharField(max_length = 50, verbose_name = "İsim")
    comment_content = models.CharField(max_length = 200, verbose_name = "Yorum")
    created_date = models.DateTimeField(auto_now_add= True, verbose_name = "Tarih")
    def __str__(self):
        return self.comment_content
    class Meta():
        ordering = ['-created_date']

article/forms.py
from django import forms
from .models import Article

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ["category", "title", "content", "article_image"]

article/views.py
from django.shortcuts import render, HttpResponse, redirect, get_object_or_404
from django.contrib import messages
from . import forms
from .models import Article, Comment, Category
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator

# Create your views here.
def index(request):
    keyword = request.GET.get("keyword")
    if keyword:
        articles = Article.objects.filter(title__contains = keyword)
        paginator = Paginator(articles, 10)
        page = request.GET.get('page')
        contacts = paginator.get_page(page)
        return render(request, "articles.html", {"contacts": contacts, "keyword": keyword})
    articles = Article.objects.all()
    paginator = Paginator(articles, 5)
    page = request.GET.get('page')
    contacts = paginator.get_page(page)
    categories = Category.objects.all()
    comments = Comment.objects.all()
    paginator = Paginator(comments, 5)
    page = request.GET.get('page')
    comments_5 = paginator.get_page(page)
    context = {
        "contacts": contacts,
        "categories": categories,
        "comments": comments_5,
        "articles": articles
    }
    return render(request, "index.html", context)

def about(request):
    keyword = request.GET.get("keyword")
    if keyword:
        articles = Article.objects.filter(title__contains = keyword)
        paginator = Paginator(articles, 10)
        page = request.GET.get('page')
        contacts = paginator.get_page(page)
        return render(request, "articles.html", {"contacts": contacts, "keyword": keyword})
    return render(request, "about.html")

def categories(request):
    keyword = request.GET.get("keyword")
    if keyword:
        articles = Article.objects.filter(title__contains = keyword)
        paginator = Paginator(articles, 10)
        page = request.GET.get('page')
        contacts = paginator.get_page(page)
        return render(request, "articles.html", {"contacts": contacts, "keyword": keyword})
    articles = Article.objects.all()
    categories = Category.objects.all()
    context = {
        "articles": articles,
        "categories": categories
    }
    return render(request, "categories.html", context)

@login_required(login_url = "user:login")
def dashboard(request):
    articles = Article.objects.filter(author = request.user)
    context = {
        "articles": articles
    }
    return render(request, "dashboard.html", context)

@login_required(login_url = "user:login")
def addarticle(request):
    form = forms.ArticleForm(request.POST or None,request.FILES or None)

    context = {
        "form": form
    }

    if form.is_valid():
        article = form.save(commit=False)
        article.author = request.user
        article.seo = article.title.replace(" ", "-")
        article.seo = article.seo.replace("ı", "i")
        article.seo = article.seo.replace("ğ", "g")
        article.seo = article.seo.replace("Ğ", "G")
        article.seo = article.seo.replace("ü", "u")
        article.seo = article.seo.replace("Ü", "U")
        article.seo = article.seo.replace("Ş", "S")
        article.seo = article.seo.replace("ş", "s")
        article.seo = article.seo.replace("İ", "I")
        article.seo = article.seo.replace("Ö", "O")
        article.seo = article.seo.replace("ö", "o")
        article.seo = article.seo.replace("Ç", "C")
        article.seo = article.seo.replace("ç", "c")
        article.seo = article.seo.replace(",", "")
        list = article.content.split(" ")
        article.read = int(((len(list)) / 200) + 1)
        article.views = 0
        article.save()

        messages.success(request, "Yazı kaydedildi!")
        return redirect("/articles/dashboard")

    return render(request, "addarticle.html", context)

def details(request, slug, title):
    keyword = request.GET.get("keyword")
    if keyword:
        articles = Article.objects.filter(title__contains = keyword)
        paginator = Paginator(articles, 10)
        page = request.GET.get('page')
        contacts = paginator.get_page(page)
        return render(request, "articles.html", {"contacts": contacts, "keyword": keyword})
    list = (Category.objects.all())
    for i in list:
        k = i.slug
        if slug == str(k):
            article = get_object_or_404(Article, seo = title, category = i)
            comments = article.comments.all()
            context = {
                "article": article,
                "comments": comments
            }
            article.views = article.views + 1
            article.save()
            return render(request, "detail.html", context)
    article.views = article.views + 1
    article.save()
    return render(request, "detail.html", context)

@login_required(login_url = "user:login")
def updateArticle(request, id):
    article = get_object_or_404(Article, id = id)
    form = forms.ArticleForm(request.POST or None, request.FILES or None, instance=article)
    if form.is_valid():
        article = form.save(commit=False)
        article.author = request.user
        article.save()

        messages.success(request, "Yazı güncellendi!")
        return redirect("article:dashboard")
    return render(request, "update.html", {"form": form})

@login_required(login_url = "user:login")
def deleteArticle(request, id):
    article = get_object_or_404(Article, id = id)
    article.delete()
    messages.success(request, "Yazı silindi!")
    return redirect("article:dashboard")

def articles(request):
    keyword = request.GET.get("keyword")
    if keyword:
        articles = Article.objects.filter(title__contains = keyword)
        paginator = Paginator(articles, 10)
        page = request.GET.get('page')
        contacts = paginator.get_page(page)
        return render(request, "articles.html", {"contacts": contacts, "keyword": keyword})
    articles = Article.objects.all()
    paginator = Paginator(articles, 5)
    page = request.GET.get('page')
    contacts = paginator.get_page(page)
    return render(request, "articles.html", {"contacts": contacts})

def show_category(request, slug):
    keyword = request.GET.get("keyword")
    if keyword:
        articles = Article.objects.filter(title__contains = keyword)
        paginator = Paginator(articles, 10)
        page = request.GET.get('page')
        contacts = paginator.get_page(page)
        categoryList = Category.objects.all()
        return render(request, "articles.html", {"contacts": contacts, "keyword": keyword, "categoryList": categoryList})
    list = (Category.objects.all())
    for i in list:
        k = i.slug
        if slug == str(k):
            articles = Article.objects.filter(category = i)
            paginator = Paginator(articles, 5)
            page = request.GET.get('page')
            contacts = paginator.get_page(page)
            categoryList = Category.objects.all()
            context = {
                "contacts": contacts,
                "categoryName": i,
                "categoryList": categoryList,
            }
            return render(request, "category.html", context)

    return render(request, "index.html")

def addComment(request, id):
    article = get_object_or_404(Article, id = id)
    slug = article.category.slug
    title = article.seo
    if request.method == "POST":
        comment_author = request.POST.get("comment_author")
        comment_context = request.POST.get("comment_context")

        newComment = Comment(comment_author = comment_author, comment_content = comment_context)
        newComment.article = article
        newComment.save()

    return redirect("/" + str(slug) + "/" + str(title) + "/")

templates/about.html
{% extends 'layout.html' %}

{% block title %}
JFBlog - Hakkımda
{% endblock title %}

{% block body %}
    <h3>Hakkımızda</h3>
    <hr>
{% endblock body %}

templates/addarticle.html
{% extends "layout.html" %}

{% block body %}
{% load crispy_forms_tags %}
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <h3>Yazı Ekle</h3>
            <hr>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{form.media}}
                {{form|crispy}}
                <br>
                <button type="submit" class="btn btn-danger">Yazı Ekle</button>
            </form>
        </div>
    </div>
{% endblock body %}

templates/articles.html
{% extends "layout.html" %}

{% block title %}
JFBlog - Son Yazılar
{% endblock title %}

{% block body %}
    {% if keyword %}
        <h3>Aranan kelime: {{keyword}}</h3>
    {% endif %}
    <br>
    {% if contacts %}
        <div class="row">
            <div class="col-lg-8">
                {% for article in contacts %}
                    <h3 id = "h01" ><a id = "a01" href="/{{article.category.slug}}/{{article.seo}}">{{article.title}}</a></h3>
                    {% if article.category.parent %}
                        <i class="fas fa-grip-lines"></i> Kategori: <a id = "a01" href = "/{{article.category.parent.slug}}">{{article.category.parent}}</a> / <a id = "a01" href="/{{article.category.slug}}">{{article.category.slug2}}</a>, {{article.created_date}}
                    {% else %}
                        <i class="fas fa-grip-lines"></i> Kategori: <a id = "a01" href="/{{article.category.slug}}">{{article.category.slug2}}</a>, {{article.created_date}}
                    {% endif %}
                    {% if article.article_image %}
                        <img class="img-fluid rounded" src="{{article.article_image.url}}" alt="">
                    {% endif %}
                    <p class="lead">
                        {{article.content|safe|truncatewords:25}} 
                        <a id = "a01" href="/{{article.category.slug}}/{{article.seo}}" style = "padding-left: 15px;">Devamını Oku</a>
                    </p>
                    <span><i class="fas fa-user-edit"></i> {{article.author}}  |  <i class="fa fa-eye"></i> {{article.views}}  |  <i class="fas fa-comments"></i> {{article.comments.all.count}} | <i class="fas fa-stopwatch"></i> {{article.read}} min read</span>
                    <hr>
                {% endfor %}
                <span>
                    {% if contacts.has_previous %}
                        <a href="?page=1">&laquo; first</a>
                        <a href="?page={{ contacts.previous_page_number }}">previous</a>
                    {% endif %}
            
                    <span class="current">
                        Sayfa {{ contacts.number }}
                    </span>
            
                    {% if contacts.has_next %}
                        <a href="?page={{ contacts.next_page_number }}">next</a>
                        <a href="?page={{ contacts.paginator.num_pages }}">last &raquo;</a>
                    {% endif %}
                </span>
            </div>
        </div>
    {% else %}
        <div class="alert alert-danger">Herhangi bir yazı bulunmuyor!</div>
    {% endif %}
    
{% endblock body %}

templates/categories.html
{% extends "layout.html" %}

{% block title %}
        JFBlog - Kategoriler
{% endblock title %}

{% block body %}
   
    {% for category in categories %}

        <div class="card my-4" style = "width: 330px; float:left;">
            <h5 class="card-header"> <i class="fas fa-list-ul"></i> <a id = "a01" href = "/{{category.slug}}">{{category.slug2}}</a></h5>
            <div class="card-body" style="padding: 15px;">
                {% for article in articles %}
                    {% if article.category == category %}
                        <i class="fas fa-dot-circle"></i> <a id = "a01" href="/{{article.category.slug}}/{{article.seo}}">{{article}}</a>
                        <br>
                    {% endif %}
                {% endfor %}
            </div>
        </div>


    {% endfor %}

{% endblock body %}

templates/category.html
{% extends "layout_index.html" %}

{% block title %}
	{{categoryName.slug2}}
{% endblock title %}

{% block body %}

    <h3>
	{% if categoryName.parent %}
		Kategori: <a id = "a01" href = "/{{categoryName.parent.slug}}">{{categoryName.parent}}</a> / <a id = "a01" href="/{{categoryName.slug}}">{{categoryName.slug2}}</a>
        {% else %}
		Kategori: <a id = "a01" href="/{{categoryName.slug}}">{{categoryName}}</a>
    		{% for category in categoryList %}
			{% if category.parent == categoryName %}
				<br> &emsp; <i class="fas fa-grip-lines"></i> <a id = "a01" href="/{{category.slug}}">{{category.slug2}}</a>
			{% endif %}
		{% endfor %}
	{% endif %}
    </h3>
    {% if contacts %}

    <div class="card my-4" style = "width: 250px; float:left;">
        <h5 class="card-header"><i class="fas fa-list-ul"></i>  Başlıklar</h5>
        <div class="card-body" style="padding: 15px;">
            <a id = "a01" href = "/{{category.slug}}">{{category.slug2}}</a>
            {% for article in contacts %}
                <i class="fas fa-dot-circle"></i>  <a id = "a01" href="/{{article.category.slug}}/{{article.seo}}">{{article}}</a>
                <br>
            {% endfor %}
        </div>
    </div>
    <br>
        <div class="row" style="padding-left: 15px;">
            <div class="col-lg-8">
                {% for article in contacts %}
                    <h3 id = "h01" ><a id = "a01" href="/{{article.category.slug}}/{{article.seo}}">{{article.title}}</a></h3>
                    {% if article.category.parent %}
                        <i class="fas fa-grip-lines"></i> Kategori: <a id = "a01" href = "/{{article.category.parent.slug}}">{{article.category.parent}}</a> / <a id = "a01" href="/{{article.category.slug}}">{{article.category.slug2}}</a>, {{article.created_date}}
                    {% else %}
                        <i class="fas fa-grip-lines"></i>  Kategori: <a id = "a01" href="/{{article.category.slug}}">{{article.category}}</a>, {{article.created_date}}
                    {% endif %}
                    {% if article.article_image %}
                        <img class="img-fluid rounded" src="{{article.article_image.url}}" alt="">
                    {% endif %}
                    <p class="lead">
                        {{article.content|safe|truncatewords:25}}
                        <a id = "a01" href="/{{article.category.slug}}/{{article.seo}}" style = "padding-left: 15px;">Devamını Oku</a>
                    </p>
                    <br>
                    <span><i class="fas fa-user-edit"></i> {{article.author}}  |  <i class="fa fa-eye"></i> {{article.views}}  |  <i class="fas fa-comments"></i> {{article.comments.all.count}} | <i class="fas fa-stopwatch"></i> {{article.read}} min read</span>
                    <hr>
                {% endfor %}
                <span>
                    {% if contacts.has_previous %}
                        <a href="?page=1">&laquo; first</a>
                        <a href="?page={{ contacts.previous_page_number }}">previous</a>
                    {% endif %}
            
                    <span class="current">
                        Sayfa {{ contacts.number }}
                    </span>
            
                    {% if contacts.has_next %}
                        <a href="?page={{ contacts.next_page_number }}">next</a>
                        <a href="?page={{ contacts.paginator.num_pages }}">last &raquo;</a>
                    {% endif %}
                </span>
            </div>
        </div>
    {% endif %}
    
{% endblock body %}

templates/dashboard.html
{% extends "layout.html" %}

{% block body %}
    <h3>Kontrol Paneli</h3>
    <hr>
    <p>Hoşgeldin <small>{{request.user.username}}</small></p>
    <hr>
    {% if articles %}
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">id</th>
                    <th scope="col">Başlık</th>
                    <th scope="col">Görüntülenme</th>
                    <th scope="col">Yorum Sayısı</th>
                    <th scope="col">Tarih</th>
                    <th scope="col">Güncelle</th>
                    <th scope="col">Sil</th>
                </tr>
            </thead>
            <tbody>
                {% for article in articles %}
                    <tr>
                        <th scope="row">{{article.id}}</th>
                        <td><a href="/{{article.category.slug}}/{{article.seo}}">{{article.title}}</a></td>
                        <td>{{article.views}}</td>
                        <td>{{article.comments.all.count}}</td>
                        <td>{{article.created_date}}</td>
                        <td><a class="btn btn-danger" href="{% url 'article:update' article.id %}">Güncelle</a></td>
                        <td><a class="btn btn-danger" href="{% url 'article:delete' article.id %}">Sil</a></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% endif %}
    <br>
    <a class="btn btn-danger" href="{% url 'article:addarticle' %}">Yazı Ekle</a>
{% endblock body %}

templates/detail.html
{% extends "layout.html" %}

{% block title %}
	{{article.title}}	
{% endblock title %}

{% block body %}
    <div class="row">
      <div class="col-lg-8">
            <h1 class="mt-4">{{article.title}}</h1>
            <p class="lead">
            <i class="fas fa-grip-lines"></i>
            Kategori: 
            {% if article.category.parent %}
                <a id = "a01" href = "/{{article.category.parent.slug}}">{{article.category.parent}}</a> / <a id = "a01" href="/{{article.category.slug}}">{{article.category.slug2}}</a>
            {% else %}
                <a id = "a01" href="/{{article.category.slug}}">{{article.category}}</a>
            {% endif %}
            , {{article.created_date}}
            , <a id = "a01" href="#">{{article.author}}</a>
            </p>
            <hr>
            {% if article.article_image %}
                <img class="img-fluid rounded" src="{{article.article_image.url}}" alt="">
            {% endif %}
            <p class="lead">
                {{article.content|safe}}
            </p>
            <hr>
            <h5>Yorumlar</h5>
            <br>
            {% if comments %}
                {% for comment in comments %}
                    <div class="media mb-4">
                        <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" l>
                        <div class="media-body">
                            <h5 class="mt-0">{{comment.comment_author}}</h5>
                            {{comment.comment_content}}
                            <p style="float: right;">{{comment.created_date}}</p>
                        </div>
                    </div>
                {% endfor %}
            {% else %}
                <div class="alert alert-danger">Henüz bir yorum bulunmuyor.</div>
            {% endif %}
            <div class="card my-4">
                <h5 class="card-header">Yorum bırakın</h5>
                <div class="card-body" style="padding: 15px;">
                    <form method="POST" action="{% url 'article:comment' article.id %}">
                        {% csrf_token %}
                        <label>İsim:</label>
                        <div class="form-group">
                            <input type="text" class="form-control" style="width: 250px;" name="comment_author">
                        </div>
                        <label>Yorum:</label>
                        <div class="form-group">
                            <textarea class="form-control" rows="3" name="comment_context"></textarea>
                        </div>
                        <button type="submit" class="btn btn-danger" style="float: right;">Ekle</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock body %}

templates/index.html
{% extends 'layout_index.html' %}

{% block title %}
        JFBlog - Index
{% endblock title %}

{% block body %}

    <div class="card my-4" style = "width: 250px; float:left;">
        <h5 class="card-header"><i class="fas fa-list-ul"></i> Kategoriler</h5>
        <div class="card-body" style="padding: 15px;">
            {% for category in categories %}
                <a id = "a01" href = "/{{category.slug}}">{{category.slug2}}</a>
                <hr>
                {% for article in articles %}
                    {% if article.category == category %}
                        <i class="fas fa-dot-circle"></i> <a id = "a01" href="/{{article.category.slug}}/{{article.seo}}">{{article}}</a>
                        <br>
                    {% endif %}
                {% endfor %}
                <hr>
            {% endfor %}
        </div>
	<h5 class="card-header"><i class="fas fa-list-ul"></i> Son Yorumlar</h5>
        <div class="card-body" style="padding: 15px;">
            {% for comment in comments%}
                <i class="far fa-comment"></i> {{comment.comment_content}} | <a id = "a01" href = "/{{comment.article.category.slug}}/{{comment.article.seo}}">{{comment.article}}</a>
                <br>
            {% endfor %}
        </div>
    </div>
   <br>
    <div class="row" style = "padding-left: 25px;">
        <div class="col-lg-8">
            {% for article in contacts %}
                <h3 id = "h01" ><a id = "a01" href="/{{article.category.slug}}/{{article.seo}}">{{article.title}}</a></h3>
                {% if article.category.parent %}
                    <i class="fas fa-grip-lines"></i> Kategori: <a id = "a01" href = "/{{article.category.parent.slug}}">{{article.category.parent}}</a> / <a id = "a01" href="/{{article.category.slug}}">{{article.category.slug2}}</a>, {{article.created_date}}
                {% else %}
                    <i class="fas fa-grip-lines"></i> Kategori: <a id = "a01" href="/{{article.category.slug}}">{{article.category}}</a>, {{article.created_date}}
                {% endif %}
                {% if article.article_image %}
                    <img class="img-fluid rounded" src="{{article.article_image.url}}" alt="">
                {% endif %}
                <p class="lead">
                    {{article.content|safe|truncatewords:45}} 
                    <a id = "a01" href="/{{article.category.slug}}/{{article.seo}}" style = "padding-left: 15px;">Devamını Oku</a>
                </p>
                <span><i class="fas fa-user-edit"></i> {{article.author}}  |  <i class="fa fa-eye"></i> {{article.views}}  |  <i class="fas fa-comments"></i> {{article.comments.all.count}} | <i class="fas fa-stopwatch"></i> {{article.read}} min read</span>
                <hr>
            {% endfor %}
        </div>
    </div>

{% endblock body %}

templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="shortcut icon" type="image/x-icon" href="/media/favicon.ico"/>
    <script src="https://kit.fontawesome.com/5bbccb4e82.js"></script>
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    {% include "includes/navbar.html" %}

    <div class="container">

        {% if messages %}
            {% for message in messages %}
            <div {% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>{{ message }}</div>
            {% endfor %}
        {% endif %}

        <br>
        
        {% block body %}
        
        {% endblock body %}
    </div>

<footer id="sticky-footer" class="py-4 bg-dark text-white-50">
    <div class="container text-center">
            <small>Copyright &copy; janfranco.com | <a href="/sitemap.xml">SiteMap</a> | Contact : poisonweeb@gmail.com</small>
    </div>
  </footer>


    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/gh/google/code-prettify@master/loader/run_prettify.js"></script>
</body>
</html>

templates/login.html
{% extends 'layout.html' %}

{% block body %}
{% load crispy_forms_tags %}

    <div class="row">
        <div class="col-md-6 offset-md-3">
            <h3>Giriş Yap</h3>
            <hr>
            <form method="post">
                {% csrf_token %}
                {{form|crispy}}
                <br>
                <button type="submit" class="btn btn-danger">Giriş Yap</button>
            </form>
        </div>
    </div>

{% endblock body %}